name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        env-version: 
          - os: "ubuntu-latest"
            python: 3.6
          - os: "ubuntu-latest"
            python: 3.9
          - os: "windows-latest"
            python: 3.9
          - os: "macos-latest"
            python: 3.9

    runs-on: ${{ matrix.env-version.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.env-version.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.env-version.python }}

      - name: setup pip
        run: python -m pip install --upgrade pip

      - name: install
        run: make install-dev

      - name: lint
        run: make lint

      - name: coverage
        run: make coverage
