name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os-version: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: [3.6, 3.9]

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: sudo make install-dev

      - name: lint
        run: make lint

      - name: coverage
        run: make coverage
